version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Rails-myapp
    runas: ubuntu
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/Application.sh
      #runas: ubuntu
  #ApplicationStart:
    #- location: scripts/ApplicationStart.sh
    #  runas: ubuntu