version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Rails-myapp
    runas: ubuntu
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      runas: ubuntu